pchapin@sover.net
=====
Peter.Chapin@vtc.vsc.edu
=====
Message-ID: <4B315418.3020206@sover.net>
Date: Tue, 22 Dec 2009 18:19:52 -0500
From: "Peter C. Chapin" <pchapin@sover.net>
User-Agent: Thunderbird 2.0.0.23 (Windows/20090812)
MIME-Version: 1.0
To: Peter Chapin <Peter.Chapin@vtc.vsc.edu>
Subject: Test #2
X-Enigmail-Version: 0.96.0
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
</head>
<body bgcolor="#ffffff" text="#000000">
This is a second test message sent through my local SMTP server.<br>
<br>
Peter<br>
<br>
</body>
</html>
